repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: "StoneSoup/"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ["filter-files"]
        exclude: "StoneSoup/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
        language_version: python3
        exclude: "StoneSoup/"
      - id: check-added-large-files
        args: ['maxkb=10000']
        language_version: python3
        exclude: "StoneSoup/"
      - id: check-ast
        language_version: python3
        exclude: "StoneSoup/"
      - id: check-yaml
        language_version: python3
        exclude: "StoneSoup/"
      - id: check-json
        language_version: python3
        exclude: "StoneSoup/"
      - id: detect-private-key
        language_version: python3
        exclude: "StoneSoup/"
      - id: flake8
        language_version: python3


  - repo: https://github.com/Diaoul/pre-commit-hooks-poetry
    rev: 0.5.0
    hooks:
      - id: poetry-export
        args: ["without-hashes"]
